config/routes.rb
Rails.application.routes.draw do
  root 'forum#index'

  get '/help', to: 'forum#index', name: "forum"
  resources :users
  get '/users', to: 'users#index'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/logout', to: 'sessions#destroy'

  resources :snapshots do
    resources :comments, only: [:create, :update, :destroy, :edit]
  end
  resources :snapshots, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
    has_one_attached :avatar
    # avatar có thể trống
    before_save :set_default_avatar
    has_many :snapshots, dependent: :destroy



    has_many :active_relationships, class_name:     "Relationship", 
                                    foreign_key:    "follower_id", 
                                    dependent:      :destroy

    has_many :passive_relationships, class_name:    "Relationship", 
                                     foreign_key:   "followed_id",
                                     dependent:      :destroy
    has_many :following, through:  :active_relationships, source: :followed
    has_many :followers, through:  :passive_relationships, source: :follower



    before_save {self.email = email.downcase}
    validates :name, presence: true, length: {maximum: 60}
    validates :email, presence: true, length: {maximum: 255},
                      uniqueness: true
    has_secure_password
    validates :password, presence: true, length: {maximum: 10}, allow_nil:true

    def User.digest(string)
        const = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.const
        BCrypt::Password.create(string, cost: cost)
    end

    def feed
        Snapshot.where("user_id IN (?) OR user_id =?", following_ids, id)
    end

    def follow(other_user)
        following << other_user
    end

    def unfollow(other_user)
        following.delete(other_user)
    end

    def following?(other_user)
        following.include?(other_user)
    end

    def set_default_avatar
        unless avatar.attached?
          image_path = Rails.root.join("app", "assets", "images", "avatar_default", "avt.png")
          image = File.open(image_path)
          avatar.attach(io: image, filename: "default_avatar.png", content_type: 'image/png')
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user,  only: [:index, :edit, :update, :destroy]
  before_action :correct_user,    only: [:edit, :update]
  before_action :admin_user,      only: :destroy
  def index
    @user = User.find_by(params[:id])
    @users = User.paginate(page: params[:page])
  end  

  def show
    @user = User.find(params[:id])
    @snapshot = current_user.snapshots.build if logged_in?
    @snapshots = @user.snapshots
  end

  def signup
    @user = User.new
  end

  def new
    @user = User.new
  end


  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    @user.avatar.attach(params[:user][:avatar])
    if @user.save
      log_in @user
      flash[:success] = "welcome"
      redirect_to root_path
    else
      flash[:danger] = "Nhập sai"
      redirect_to signup_path
    end
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Đã chỉnh sửa thông tin"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    user = User.find(params[:id]).destroy
    flash[:success] = "Người dùng đã được xóa thành công."
    redirect_to users_path
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :avatar)
      rescue ActionController::ParameterMissing
        ActionController::Parameters.new({})
    end

    def correct_user
      @user = User.find(params[:id])
      unless current_user == @user
        flash[:error] = "Bạn không có quyền truy cập vào trang này."
        redirect_to root_path
      end
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_avatar.html.erb
<div class="update_avatar" id="div_hide_click">
    <%= form_with(model: @user, url: user_path(@user), method: :patch, local: true) do |form| %>
        <%= form.file_field :avatar, class:"chosse_image_avt" %>
        <input type="button" onclick="hideDiv()" value="Hủy"></input>
        <%= form.submit 'Lưu' %>
    <% end %>
</div>

app/views/users/_form_signup.html.erb
<%= form_with(model: @user) do |form| %>
  <%= render 'shared/error_messages' %>

  <div>
    <%= form.label :name%>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div>
    <%= form.label :password_confirmation %>
    <%= form.text_field :password_confirmation %>
  </div>
  
  <div>
    <%= form.submit %>
  </div>

<% end %>

app/views/users/_user.html.erb
<div class="row" id="<%= dom_id user %>">

  <div class="col-6"><%= link_to user.name, user %></div>
  <div class="col-6">
    <% if current_user.admin? %>
      <%= link_to "delete", user, method: :delete, data: { confirm: "chac chan xoa?" } %>
    <% end %>
  </div>
  <hr>
</div>

app/views/users/_user_infor.html.erb
<div>
        <%= image_tag @user.avatar if @user.avatar.attached? %>
        <%= link_to @user.name, user_path(@user) %>
        <% if current_user?(@user) %>
            <%= render 'users/avatar' %>
        <% end %>

        <hr>
        
        <p> 
            <b>Số bài đăng:</b> <%= @user.snapshots.count %>
        </p>
        
            <% if current_user?(@user) %>
                <%= link_to "Chỉnh sửa thông tin", edit_user_path(current_user) %>
            <% end %>
        <br>
</div>

app/views/users/edit.html.erb
<% provide(:title, "Chỉnh sửa thông tin") %>


<div class="row">
  <div class="col-4">
    <%= render 'users/user_infor' %>
  </div>
  <div class="col-4 my_container container_edit_user">
    <div class="">
      <center><h3>Chỉnh sửa thông tin</h3></center>
      <hr>
      <%= form_with(model: @user, local: true) do |form| %>
        <%= render 'shared/error_messages', object: form.object %>
        <div class="row item_edit_pf">
          <div class="inputbox">
            <%= form.text_field :name, required: true %>
            <span>Tên</span>
            <i></i>
          </div>
          <div class="inputbox">
            <%= form.text_field :email, required: true %>
            <span>Email</span>
            <i></i>
          </div>
          <div class="inputbox">
            <%= form.password_field :password, required: true %>
            <span>Mật khẩu</span>
            <i></i>
          </div>
          <div class="inputbox">
            <%= form.password_field :password_confirmation, required: true %>
            <span>Nhập lại mật khẩu</span>
            <i></i>
          </div>
          <div class="col-7"></div>
          <div class="col-5">
            <%= form.submit "Thay đổi", class:"change_edit_pf" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="col-4"></div>
</div>

app/views/users/index.html.erb
<div class="row">
  <div class="col-1"></div>
  <div class="col-2"><h5 class="my_container box_shadow">Quản lí người dùng</h5></div>
  <div class="col-7 my_container">
    <div class="row list_users">
      <h5 class="col-1"> Ảnh </h5>
      <h5 class="col-3"> Tên </h5>
      <h5 class="col-5"> Email </h5>
      <h5 class="col-2"> Số bài đăng </h5>
      <h5 class="col-1"> ID </h5>
      <hr class="col-11">

      <% @users.each do |user| %>
        <li class="col-1"> <%= image_tag user.avatar %> </li>
        <li class="col-3"> <%= user.name %> </li>
        <li class="col-5"> <%= user.email %> </li>
        <li class="col-2"> <%= @user.snapshots.count %> </li>
        <li class="col-1"><%= link_to user.id, user %></li>
      <% end %>
    </div>

    <%= link_to "New user", new_user_path %>
  </div>

  <div class="col-2"></div>
</div>

app/views/users/new.html.erb
<% provide(:title, "Sign up") %>
      <center>
      <h4 class="title_login">Sign up</h4>
      <hr>
      <%= form_with(model: @user, local: true) do |form| %>

            <p>Name<%= form.text_field :name %></p>

            <p>Email<%= form.text_field :email %></p>

            <p>Password<%= form.password_field :password %></p>

            <p>Password confirmation<%= form.password_field :password_confirmation %></p>

            <%= form.submit "Sign up" %>


        <%= link_to "Login", login_path %>
      <% end %>
      </center>

app/views/users/show.html.erb
<% provide(:title, "Profile") %>

<center>
  <div class="col-5">
    <%= render 'users/user_infor' %>
  </div>
</center>