config/routes.rb
Rails.application.routes.draw do
  root 'forum#index'

  get '/help', to: 'forum#index', name: "forum"
  resources :users
  get '/users', to: 'users#index'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/logout', to: 'sessions#destroy'

  resources :snapshots do
    resources :comments, only: [:create, :update, :destroy, :edit]
  end
  resources :snapshots, only: [:create, :destroy]
end

app/models/snapshot.rb
class Snapshot < ApplicationRecord
  has_many :comments, dependent: :destroy
  belongs_to :user
  has_one_attached :image
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 250 }

  validates :image, #content_type: { in: [image/jpeg, image/gif, image/png ], message: "jpeg, gif, png"},
                                  size: {less_than: 5.megabytes, message: "5MB!"}

  #def display_image
  #  image.variant(resize_to_limit: [500, 500])
  #end
end

app/controllers/snapshots_controller.rb
class SnapshotsController < ApplicationController
    before_action :logged_in_user, only: [:create, :destroy]
    before_action :correct_user, only: :destroy
    def create
        @snapshot = current_user.snapshots.build(snapshot_params)
        @snapshot.image.attach(params[:snapshot][:image])
        if @snapshot.save
            flash[:success] = "Đã đăng"
            redirect_back(fallback_location: root_url)
        else
            @feed_items = current_user.feed.paginate(page: params[:page])
            flash[:danger] = "Bài viết chưa có nội dung!"
            redirect_back(fallback_location: root_url)
        end
    end

    def destroy
        @snapshot.destroy
        flash[:success] = "Đã xóa bài viết"
        redirect_back(fallback_location: root_url)
    end

    private

    def snapshot_params
        params.require(:snapshot).permit(:content, :image)
    end

    def correct_user
        if current_user.admin?
            @snapshot = Snapshot.find_by(id: params[:id])
        else
            @snapshot = current_user.snapshots.find_by(id: params[:id])
            redirect_to root_url if @snapshot.nil?
        end
    end

end

app/helpers/snapshots_helper.rb
module SnapshotsHelper
end

app/views/snapshots/_count.html.erb
<div class="stats">
    <a href="<%= liked_user_path(@user) %>">
        <strong id="liked">
            <%= @snapshot.liked.count %>
        </strong>
        liked
    </a>

app/views/snapshots/_feed.html.erb
<% if @feed_items.any? %>
    <% @feed_items.each do |item| %>
        <div>
            <div class="row">
                <div class="col-12">
                    <p>
                    <%= link_to item.user do %>
                        <%= image_tag item.user.avatar if item.user.avatar.attached? %>
                    <% end %>
                    </p>
                    <p><%= item.user.name %>
                    <%= time_ago_in_words(item.created_at) %>
                    <% if current_user.admin? %>
                        <%= link_to " Delete", item, method: :delete %>
                    <% end %>
                    </p>
                </div>
                <div class="col-12">
                    <p><%= item.content %></p>
                    <%= image_tag item.image if item.image.attached? %> 
                </div>
            </div>

            <hr> 

            <div class="row">
                <span class="col-12">Comment</span>
                <% item.comments.each do |comment| %>
                    <div class="col-1">
                        <%= link_to comment.user do %>
                            <%= image_tag comment.user.avatar if comment.user.avatar.attached? %>
                        <% end %>
                    </div>
                    <div class="col-9">
                        <div>
                            <p><strong><%= comment.user.name %></strong></p>
                            <%= comment.content %>
                        </div>
                    </div>
                        <%= link_to "Delete", snapshot_comment_path(item, comment), method: :delete, data: { confirm: "Xóa bình luận?" } %>
                    </div>
                <% end %>
            </div>

            <div class="row">
                <div class="col-2">
                    <%= image_tag current_user.avatar if current_user.avatar.attached? %>
                </div>
                <div class="col-10">
                        <%= form_with(model: [item, Comment.new], url: snapshot_comments_path(item)) do |form| %>
                            <div class="row">
                                <div class="col-12">
                                    <%= form.text_area :content %>
                                </div>
                                <div class="col-8"></div>
                                <div class="col-4">
                                    <%= form.submit 'Comment'%>
                                </div>
                            </div>
                        <% end %>
                </div>
            </div>


        </div>
      <% end %>
<% end %>

app/views/snapshots/_snapshot.html.erb
<div id="snapshot-<%= snapshot.id %>">
    <div class="row">
        <div class="col-2">
            <%= link_to snapshot.user do %>
                <div">
                    <%= image_tag @user.avatar if @user.avatar.attached? %>
                </div>
            <% end %>
        </div>
        <div class="col-10">
            <div class="row">
                <div class="col-10">
                    <%= @user.name %>
                </div>

                <div class="col-2"> 
                    <ul>
                        <% if current_user?(snapshot.user) or current_user.admin? %>
                            <li><i class="fa-solid fa-trash"></i> <%= link_to " Xóa", snapshot, method: :delete, style:"color: #000000; background: none;" %><li>
                        <% end %>
                    </ul>
                </div>

                <div class="col-12">
                    <small><i class="fa-solid fa-clock" style="color: #404040;"></i>  <%= time_ago_in_words(snapshot.created_at) %> </small>
                </div>
            </div>
        </div>

        <div class="col-12">
            <p><%= snapshot.content %></p>
            <div> 
                <%= image_tag snapshot.image if snapshot.image.attached? %>
            </div>
        </div>
    </div>

    <hr>
    
    <div class="row">
        <span class="col-12">Comment</span>
        <% snapshot.comments.each do |comment| %>
            <div class="col-1 fix_padding_col_cmt">
                <%= link_to comment.user do %>
                    <%= image_tag comment.user.avatar, class:"avt_comment" if comment.user.avatar.attached? %>
                <% end %>
            </div>
            <div class="col-9">
                <div>
                    <li><strong><%= comment.user.name %></strong></li>
                    <%= comment.content %>
                </div>
            </div>
            <div class="col-2">
                <div>
                    <div>
                        <%= link_to "Delete", snapshot_comment_path(snapshot, comment), method: :delete, data: { confirm: "Xóa bình luận?" } %>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
    
    <hr>

    <div class="row">
        <div class="col-2">
            <div class="avatar_wrapper">
                <%= image_tag current_user.avatar if current_user.avatar.attached? %>
            </div>
        </div>
        <div class="col-10">
            <div class="form_comment">
                <%= form_with(model: [snapshot, Comment.new], url: snapshot_comments_path(snapshot)) do |form| %>
                    <div class="row">
                        <div class="col-12">
                            <%= form.text_area :content %>
                        </div>
                        <div class="col-8"></div>
                        <div class="col-4">
                            <span><%= form.submit 'Bình luận' %></span>
                        </div>
                    </div>
                <% end %>
            </div>
        </div>
    </div>


</div>

<br>

app/views/snapshots/_snapshot_form.html.erb
<%= form_with(model: @snapshot, local: true,) do |f| %>
    <div class="row">
        <div class="col-1"></div>
        <div class="col-11">
            <%= render 'shared/error_messages', object: f.object %>
            <%= f.text_area :content, placeholder: "New post ..." %>
        </div>

        <div class="col-9">
                <%= f.file_field :image, style:"color: #383838;" %>
        </div>
        <div class="col-3">
            <%= f.submit "Post" %>
        </div>
    </div>
    <hr>
<% end %>